version: '3.8'
services:
  minio:
    image: minio/minio:latest
    volumes:
      - minio_data:/data
    expose:
      - 9000
    ports:
      - '9000:9000'
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
    command: server /data

volumes:
  minio_data:
